### PR TITLE
Get proper cased method names

### PR DESCRIPTION
**Pull request by nuernbergerA**
`get_class_methods` will return only public accessible method
Visibility example from the [docs](https://www.php.net/manual/en/function.get-class-methods.php#95548)
[Usage](https://php-safari.com/function/get_class_methods) in laravel ecosystem

### CODE REVIEW

**Review by Naoray — APPROVED** [review]

**Comment by jasonmccreary** [comment]
If possible, it'd be nice to see some memoization here as not to run `get_class_methods` for every column. This really only needs to be run once for the entire lifecycle (i.e. `static`).

**Comment by nuernbergerA** [comment]
@jasonmccreary would it be ok for you to store it in the container?
`app()->instance('faker-methods', [])`

we could do this in `getNamesFromProvider`

**Comment by jasonmccreary** [comment]
This isn't part of a Laravel app. So there is not `app()`.

You can make the method `static` and track a `static` variable. Here's a [good article](https://eddmann.com/posts/implementing-and-using-memoization-in-php/) if you're not familiar.

**Comment by nuernbergerA** [comment]
@jasonmccreary done

**Pull request merged**
